# Generated by Django 3.1.5 on 2021-02-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
