# Generated by Django 3.1.5 on 2021-02-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210208_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
