# Generated by Django 3.1.5 on 2021-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210220_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=25, verbose_name='作者'),
        ),
    ]
