# Generated by Django 3.1.5 on 2021-02-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.ImageField(upload_to='img', verbose_name='图片'),
        ),
    ]
